Add LottieViewAnimation Example Project
EXXETA/swiftui-examples pull request #2
Opened 2024-01-17 15:21 UTC by LauraSiewert

2024-01-17 15:49 UTC, jay-k98 requested changes
Nur Kleinigkeiten hinsichtlich der Lesbarkeit, ansonsten alles gut :)

2024-01-17 15:49 UTC, jay-k98 commented on LottieAnimationExample/LottieAnimationExample/Ressources/Assets.xcassets/image.imageset/pexels-iván-cisneros-14086443 2.jpg
Warum ist das Bild hier nochmal drin? Selbe Auflösung etc.

2024-01-17 15:49 UTC, jay-k98 commented on LottieAnimationExample/LottieAnimationExample/Ressources/Assets.xcassets/image.imageset/pexels-iván-cisneros-14086443 1.jpg
Auch hier: Warum ist das Bild hier nochmal drin? Selbe Auflösung etc.

2024-01-17 15:49 UTC, jay-k98 commented on LottieAnimationExample/LottieAnimationExample/Sources/ContentView.swift
> +	/// A state variable which holds the playback mode
Es scheint mir als wären die Einrückungen ein bisschen off. Normal sind es ja 4 Leerzeichen bei Swift. Siehe z.B. die Datei untendrunter: LottieAnimationExample/LottieAnimationExample/Sources/LottieAnimationExampleApp.swift

Hier sind es ein paar mehr. Gilt dann für alle Zeilen.
Als Tipp: swiftlint installieren, Terminal beim workspace öffnen und vor dem commiten "swiftlint --fix" laufen lassen.

2024-01-17 15:49 UTC, jay-k98 commented on LottieAnimationExample/LottieAnimationExample/Sources/ContentView.swift
> +					.opacity(playbackMode != .paused ? 0.5 : 1)
hardcoded: Vllt zwei let Variablen: opacityPaused & opacityPlaying

2024-01-17 15:49 UTC, jay-k98 commented on LottieAnimationExample/LottieAnimationExample/Sources/ContentView.swift
> +					.frame(height: UIScreen.main.bounds.width)
hardcoded. Vllt vorher: let widthImage: CGFloat = UIScreen.main.bounds.width

2024-01-17 15:49 UTC, jay-k98 commented on LottieAnimationExample/LottieAnimationExample/Sources/ContentView.swift
> +					.offset(y: playbackMode != .paused ? 0 : -UIScreen.main.bounds.height)
hardcoded. Vllt let offsetPlaying: CGFloat = -UIScreen.main.bounds.height

2024-01-17 15:49 UTC, jay-k98 commented on LottieAnimationExample/LottieAnimationExample/Sources/ContentView.swift
> +					.frame(height: UIScreen.main.bounds.width - 100)
hardcoded 100 -> ich verstehe leider nicht genau, was die 100 bedeutet

2024-01-17 15:49 UTC, jay-k98 commented on LottieAnimationExample/LottieAnimationExample/Sources/ContentView.swift
> +					RoundedRectangle(cornerRadius: 16)
hardcoded. Vllt let cornerRadiusButton: CGFloat = 16

2024-01-17 15:49 UTC, jay-k98 commented on LottieAnimationExample/LottieAnimationExample/Sources/ContentView.swift
> +				.padding(16)
hardcoded. Vllt let paddingText: CGFloat = 16

2024-01-17 15:49 UTC, jay-k98 commented on LottieAnimationExample/LottieAnimationExample/Sources/ContentView.swift
> +			Text("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo du
Den Text könnte man auch als eigene Variable extrahieren für eine bessere Lesbarkeit

2024-01-17 16:01 UTC, theDeniZ approved these changes
sieht gut aus

2024-01-19 09:27 UTC, jay-k98 approved these changes
Alles erledigt!

2024-01-19 09:28 UTC, jay-k98 approved these changes
Ready for merge

2024-01-19 09:31 UTC, laurasiewertexxeta approved these changes

2024-01-19 12:18 UTC, merged